set a new func for TQDepth
cda-tum/mqt-core pull request #414
Opened 2023-09-06 08:20 UTC by avelsh

add a new feuture to count the TQDepth for TwoQubitEncoding

2023-09-27 15:23 UTC, pehamTom requested changes
Thank you for this feature. In addition to the changes below, please add some test cases to check if everything works correctly.

2023-09-27 15:23 UTC, pehamTom commented on src/operations/Operation.cpp
> +  if (!getControls().empty()) {
There are two-qubit gates that do not have a control (e.g. SWAP gate) but are still two-qubit gates.

2023-09-27 15:23 UTC, pehamTom commented on src/operations/Operation.cpp
> +void Operation::addTwoQubitDepthContribution(
This doesn't just count two-qubit gates but any gate with a control. So a multi-controlled x-gate would still be considered a two-qubit gate in this case. I actually don't think this is a huge problem but the feature and the methods should be renamed accordingly (i.e. multiQubitGateDepth or something).

2023-09-27 15:23 UTC, pehamTom commented on include/operations/Operation.hpp
> +  addTwoQubitDepthContribution(std::vector<std::size_t>& depths) const;
This feature doesn't work correctly for a `CompoundOperation`. For these the method would have to be overridden so as to recursively compute the depth.

2024-03-18 15:52 UTC, closed without merging

2024-03-18 15:52 UTC, burgholzer commented
Closing this for now, as no one seems to be actively working on it.
Feel free to re-open if this changes at any point in time.